language: ruby
cache: bundler
sudo: false

matrix:
  fast_finish: true
  allow_failures:
  include:
    - rvm: jruby-9.0.5.0
addons:
  postgresql: "9.4"

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database warehouse_test;' -U postgres

script: "bin/rspec --tag ~kafka"
